import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { TextsClient } from 'src/app/autogenerated/texts-client';

@Component({
  templateUrl: './create-text.component.html',
  styleUrls: ['./create-text.component.scss']
})
export class CreateTextComponent implements OnInit {

  textForm!: FormGroup;

  loading = false;
  success = false;

  constructor(private textsClient: TextsClient, private fb: FormBuilder) { }

  languages = [
    { value: 'en', viewValue: 'English' },
    { value: 'ru', viewValue: 'Russian' }
  ];

  ngOnInit(): void {
    this.textForm = this.fb.group({
      title: [''],
      textContent: [''],
      inputLanguage: [''],
    });
  }

  onSubmit() {

    const fromData = this.textForm.value;

    this.textsClient.createText(fromData).subscribe(response => {
      this.loading = false;
      console.log(response)
    }, err => {
      this.success = false;
    });
  }
}
