import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Text, TextsClient } from 'src/app/autogenerated/texts-client';

@Component({
  templateUrl: './create-text.component.html',
  styleUrls: ['./create-text.component.scss']
})
export class CreateTextComponent implements OnInit {

  textForm!: FormGroup;

  constructor(private textsClient: TextsClient, private fb: FormBuilder) { }

  ngOnInit(): void {
    this.textForm = this.fb.group({
      title: [''],
      textContent: [''],
      inputLanguage: [''],
    });
  }

  onSubmit() {
    this.textsClient.createText(this.textForm.value).subscribe(response => console.log(response));
  }
}
