import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { switchMap } from 'rxjs/operators';
import { Text, TextsClient } from 'src/app/autogenerated/texts-client';

@Component({
  templateUrl: './text-details.component.html',
  styleUrls: ['./text-details.component.scss']
})
export class TextDetailsComponent implements OnInit {

  //text$: Observable<Text>;

  textForm = new FormGroup({
    textName: new FormControl(''),
    text: new FormControl(''),
    inputLanguage: new FormControl('')
  });

  constructor(private textsClient: TextsClient, private route: ActivatedRoute) { }

  ngOnInit(): void {
    // this.text$ = this.route.paramMap.pipe(
    //   switchMap(params => {
    //     const id = params.get('id');
    //     return this.textsClient.getTextById(id);
    //   })
    // );

    this.route.paramMap.subscribe(params => console.log(params.get('id')));
  }

  onSubmit() {
    this.textsClient.createText(new Text({
      title: this.textForm.get('textName')?.value,
      textContent: this.textForm.get('text')?.value,
      inputLanguage: this.textForm.get('inputLanguage')?.value
    })).subscribe(response => console.log(response));
  }

}
