import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { TextsClient, Text } from '../autogenerated/texts-client';

@Component({
  selector: 'app-texts',
  templateUrl: './texts.component.html',
  styleUrls: ['./texts.component.scss']
})
export class TextsComponent implements OnInit {

  texts$: Observable<Text[]>;

  constructor(private textsClient: TextsClient) { 
    this.texts$ = this.textsClient.getTexts();
  }

  ngOnInit(): void {
  }
}
