import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { TranslationRequest, TranslatorClient } from './autogenerated/translator-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor(private translatorClient: TranslatorClient) {
    translatorClient.getWordTranslation("en", "ru", "dude").subscribe(r => console.log(r));


  }
}
